[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "task_01", "task_02"]

[workspace.dependencies]
lazy_static = "1.4.0"

[dependencies]
task_01 = { path = "task_01" }
task_02 = { path = "task_02" }
