[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "day_01", "day_02"]

[workspace.dependencies]
lazy_static = "1.4.0"
nom = "7.1.3"

[dependencies]
day_01 = { path = "day_01" }
day_02 = { path = "day_02" }
